name: Lint C# Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Run dotnet format for Project1
      run: |
        set -e
        dotnet --version
        dotnet format --version
        set +e

        if git diff --name-only HEAD..main | grep -E '\.cs$' > /dev/null; then
          echo "C# files changed, execute format:"
          git diff --name-only HEAD..main | grep -E '\.cs$' 
          git diff --name-only HEAD..main | grep -E '\.cs$' | perl -pe 'chomp; $_ .= "," unless eof' | xargs -I{} dotnet format whitespace ./Project1/Assets/Scripts --folder --verify-no-changes --verbosity diagnostic --include "{}"
        else
          echo "No C# files changed, skipping format"
          exit 0
        fi

