name: Lint C# Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  base_branch: main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Fetch branch
      run: |
        git fetch origin $base_branch

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Run dotnet format for Project1
      run: |
        set -x
        dotnet --version
        dotnet format --version
        git diff --name-only origin/$base_branch..HEAD
        set +x

        if git diff --name-only origin/$base_branch..HEAD | grep -E '\.cs$' > /dev/null; then
          echo "C# files changed, execute format:"
          git diff --name-only origin/$base_branch..HEAD | grep -E '\.cs$' 
          git diff --name-only origin/$base_branch..HEAD | grep -E '\.cs$' | perl -pe 'chomp; $_ .= "," unless eof' | xargs -I{} dotnet format whitespace ./Project1/Assets/Scripts --folder --verify-no-changes --verbosity diagnostic --include "{}"
        else
          echo "No C# files changed, skipping format"
          exit 0
        fi

